// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW74gkDR9D9AkRrITK1yWuOy7X5sq1Yyg',
    appId: '1:541039650342:web:f5e5baffa57512174968e7',
    messagingSenderId: '541039650342',
    projectId: 'dgyard-connect',
    authDomain: 'dgyard-connect.firebaseapp.com',
    storageBucket: 'dgyard-connect.firebasestorage.app',
    measurementId: 'G-8JKPZHKDWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOzuY46r0-iUR4kyB8-tlhuq8zbRchXIg',
    appId: '1:541039650342:android:85318029c60f7eba4968e7',
    messagingSenderId: '541039650342',
    projectId: 'dgyard-connect',
    storageBucket: 'dgyard-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGmQTLkajtDEYFwrJWxEI2XVpozn7IMl8',
    appId: '1:541039650342:ios:8d725f1751f53c984968e7',
    messagingSenderId: '541039650342',
    projectId: 'dgyard-connect',
    storageBucket: 'dgyard-connect.firebasestorage.app',
    iosBundleId: 'com.dgyardconnect.dgyardconnect',
  );
}
